# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoxSwift
  pod 'AEOTPTextField'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'SwiftyDraw'
  pod 'SwiftMessages'

  target 'BoxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoxSwiftUITests' do
    # Pods for testing
  end

end
